export const FIND_PROPINSI_REQUEST = 'FIND_PROPINSI_REQUEST';
export const FIND_PROPINSI_SUCCESS = 'FIND_PROPINSI_SUCCESS';
export const FIND_PROPINSI_FAILURE = 'FIND_PROPINSI_FAILURE';

export const FIND_KONTRASEPSI_REQUEST = 'FIND_KONTRASEPSI_REQUEST';
export const FIND_KONTRASEPSI_SUCCESS = 'FIND_KONTRASEPSI_SUCCESS';
export const FIND_KONTRASEPSI_FAILURE = 'FIND_KONTRASEPSI_FAILURE';

export const FIND_PEMAKAI_REQUEST = 'FIND_PEMAKAI_REQUEST';
export const FIND_PEMAKAI_SUCCESS = 'FIND_PEMAKAI_SUCCESS';
export const FIND_PEMAKAI_FAILURE = 'FIND_PEMAKAI_FAILURE';

export const SAVE_PEMAKAI_REQUEST = 'SAVE_PEMAKAI_REQUEST';
export const SAVE_PEMAKAI_SUCCESS = 'SAVE_PEMAKAI_SUCCESS';
export const SAVE_PEMAKAI_FAILURE = 'SAVE_PEMAKAI_FAILURE';
